### ISSUE TITLE
Broken Build due to Github deprecation

### ISSUE THREAD

**Issue by tomvik** [RoBorregos/Robocup-Home#100]
Github has deprecated a set of commands used on the workflow that we use for our CI. 

Remembering that our CI depends on: https://github.com/betwo/github-setup-catkin to setup ROS.

More details on the deprecation of these commands is seen in: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

The solution I propose is to create an issue on betwo's repository, fork it, and solve it.

The error looks like:
![image](https://user-images.githubusercontent.com/13770244/100031454-4d109a00-2dbb-11eb-8915-038c9390a0e9.png)

**Comment by paulvazbad** [comment]
I forked and made a hotfix:
https://github.com/paulvazbad/github-setup-catkin

**Comment by tomvik** [comment]
Niceee! Do you know if we can use your forked branch in the meanwhile for our CI?

**Comment by paulvazbad** [comment]
I believe we can use it
