### ISSUE TITLE
Bug: betwo/github-setup-catkin setting env vars depreciated in CI build

### ISSUE THREAD

**Issue by AuroTB** [RoBorregos/Robocup-Home#102]
New [updates](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) have deprecated set-env and add-path commands.

Error: https://github.com/RoBorregos/Robocup-Home/pull/101/checks?check_run_id=1615103495

A hot-fix will be to setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`, as seen in this [CL](https://github.com/RoBorregos/Robocup-Home/blob/hotfix/GitActionDeprecation/.github/workflows/catkin.yml) I've made.
<br/>
This works, because I've tried it with the current [Map Context PR](https://github.com/RoBorregos/Robocup-Home/pull/101) and it passed successfully.
Got any idea how we could use [Env Files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files) instead? This looks like an issue with  betwo.

**Comment by paulvazbad** [comment]
This is duplicated, check out [this issue](https://github.com/RoBorregos/Robocup-Home/issues/100)
