### ISSUE TITLE
PCB Electronica Potenica

### ISSUE THREAD

**Issue by Josecisneros001** [RoBorregos/robocup-home#103]
Objectives:
-  Investigación sobre los módulos de robot y sus demandas energéticas.
-  Esquemático 

De acuerdo al esquemático: [https://oshwlab.com/a00825779/home-base]
Poner a disposición:
 - 5V, 12V
 - Pines que no se usan del microcontrolador.
 - Pines I2C

Deliverables
- [ ] Documento Drive 
- [ ] Link EasyEda

**Comment by AldoSamaniego** [comment]
https://oshwlab.com/a00825779/home-base @Josecisneros001
