### ISSUE TITLE
PCB Elevador Investigación

### ISSUE THREAD

**Issue by Josecisneros001** [RoBorregos/Robocup-Home#104]
Objectives:
- Know what the PCB is supposed to make.
- Research the components that will be used.
Deliverables:
- [x] Documento Drive

**Comment by AnelAlvarado** [comment]
https://docs.google.com/document/d/1yCGWhrs2nX35uhO2GK-XCN7LZRYhebDdy1O6i61kpA4/edit?usp=sharing
