### ISSUE TITLE
Iniciar desarrollo Gripper

### ISSUE THREAD

**Issue by Josecisneros001** [RoBorregos/Robocup-Home#133]
Desarrollar Bocetos y Diseño Técnico

**Comment by AlonRuiz** [comment]
![1](https://user-images.githubusercontent.com/74417584/110585265-2f7efa80-8136-11eb-8e8f-ef7cd1791658.png)
![2](https://user-images.githubusercontent.com/74417584/110585276-3279eb00-8136-11eb-9f95-246aa7771b45.png)
![3](https://user-images.githubusercontent.com/74417584/110585282-34dc4500-8136-11eb-89e6-02b7a76ebc14.png)

**Comment by Josecisneros001** [comment]
Great Job!
