### ISSUE TITLE
Investigación Fibra Vidrio

### ISSUE THREAD

**Issue by Josecisneros001** [RoBorregos/robocup-home#134]
Desarrollar documento sobre la manufactura de fibra de vidrio.
Ver posibilidad de empezar pruebas
- Investigar método (molde + manejo de fibra)
- Desarrollar BOM
- Ver dónde podría fabricarse molde (waterjet)

**Comment by AuroTB** [comment]
Documentación de fibra de vidrio: https://docs.google.com/document/d/158ci4uIg3gkiYWl_m8CAxykUG-NU0_C73wTkkfxpXmY/edit#heading=h.h24cbcnw50rf
