### ISSUE TITLE
Desarrollo Suspensión

### ISSUE THREAD

**Issue by Josecisneros001** [RoBorregos/robocup-home#135]
- Diseño de Suspensión para mejorar agarre

Entregable:
- [ ]  Investigación/Cálculos
- [ ] Modelaje Solidworks

**Comment by AminMendez** [comment]
To begin the model of the robot suspension system first we need to calculate the teoretical values of the spring and damping constants that satisfy a smood displacement. Mathematical modeling of the four wheel system is complicated. We can simplify the sistem by only analysing one wheel as show below. 

![image](https://user-images.githubusercontent.com/47193853/110560705-0fd2dc80-810c-11eb-9276-bbe402628758.png)

A mass-spring damper system is model by the following equation: 

![image](https://user-images.githubusercontent.com/47193853/110561545-7ad0e300-810d-11eb-9136-48f83d359b3c.png)

where m is the mass that holds a wheel, K the spring constant, b the damping coeficient and r(t) the external forces.

Using Laplace transform we can conclude:

![image](https://user-images.githubusercontent.com/47193853/110560783-2d07ab00-810c-11eb-8e51-749086cfd6aa.png)

![image](https://user-images.githubusercontent.com/47193853/110560876-53c5e180-810c-11eb-9425-0950e71ddff9.png)

The transfer function is given by:

![image](https://user-images.githubusercontent.com/47193853/110561873-14989000-810e-11eb-9ed2-583b60355c27.png)

Once having the model of the system we substitute the values we have, such as the mass. As we want a smood movement the 
spring must be a systm with critical damping, So the poles of the system must be equals:

s^2 +(b/m)*s + (k/m) = (s + p)^2 

giving us the value of b as function of k and m

b= 2* m* sqrt (k/m)

By using Matlab and WolframAlpha programs I model the system to give the reaction of any input to the system with knowing the constants.
![image](https://user-images.githubusercontent.com/47193853/110564198-0fd5db00-8112-11eb-9344-ced2ad5b1859.png)
![image](https://user-images.githubusercontent.com/47193853/110564227-17957f80-8112-11eb-966d-6fe7d2fe8386.png)


My task of this week is to find the most suitable constant K for our robot, mantaining the desire stability.

**Comment by AminMendez** [comment]
Continuing with the calculus of the suspension, We develop a MATLAB program in which by a given estability time we can know the values of the spring and damping constants. The first program is simulating a Step input with a variable magnitud and the second we can give the traslational function of the wheel.

UNIT STEP
![image](https://user-images.githubusercontent.com/47193853/115486458-4c6e1980-a21c-11eb-8d8d-de161518d57d.png)

Response with unit step magnitud of 10
![image](https://user-images.githubusercontent.com/47193853/115486567-8c350100-a21c-11eb-9c80-6291ec8e0e27.png)


Given Function
![image](https://user-images.githubusercontent.com/47193853/115486368-2ba5c400-a21c-11eb-8b6a-4769a61c96ca.png)
![image](https://user-images.githubusercontent.com/47193853/115486402-38c2b300-a21c-11eb-98f0-171f9e1ea461.png)

Response with Sin (t) input
![image](https://user-images.githubusercontent.com/47193853/115486620-a4a51b80-a21c-11eb-8282-d08350f208bd.png)

Now by just given the Stability Time we can know the important constants  with a critical damping

**Comment by AldoSamaniego** [comment]
![image](https://user-images.githubusercontent.com/47438412/122481033-990f7000-cf93-11eb-9604-94d7ec8a1468.png)
![image](https://user-images.githubusercontent.com/47438412/122481038-9b71ca00-cf93-11eb-8dc1-6334038d8a2b.png)
![image](https://user-images.githubusercontent.com/47438412/122481046-9d3b8d80-cf93-11eb-9808-150de71b77a3.png)
![image](https://user-images.githubusercontent.com/47438412/122481521-76ca2200-cf94-11eb-9656-dbb6375be66e.png)
![image](https://user-images.githubusercontent.com/47438412/122481533-792c7c00-cf94-11eb-85e1-58e70802873f.png)
![image](https://user-images.githubusercontent.com/47438412/122481538-7b8ed600-cf94-11eb-8d77-d541690a5fe0.png)
![image](https://user-images.githubusercontent.com/47438412/122481624-9e20ef00-cf94-11eb-95dc-523fcc075867.png)
![image](https://user-images.githubusercontent.com/47438412/122481554-8184b700-cf94-11eb-9860-2e8b9e11b097.png)
