### ISSUE TITLE
Gripper v1

### ISSUE THREAD

**Issue by Josecisneros001** [RoBorregos/robocup-home#139]
- Desarrollar v1.0 Gripper

Entregable
- [x] Foto/Link Cad

**Comment by AlonRuiz** [comment]
![imagen](https://user-images.githubusercontent.com/74417584/112239155-8f33d600-8c0b-11eb-85e1-fd37683d4042.png)
![imagen](https://user-images.githubusercontent.com/74417584/112239177-9ce95b80-8c0b-11eb-94a8-a8ecb16ea018.png)
![imagen](https://user-images.githubusercontent.com/74417584/112239208-b094c200-8c0b-11eb-8a3d-2e6f3afa910c.png)
![imagen](https://user-images.githubusercontent.com/74417584/112239301-d8842580-8c0b-11eb-9646-062ecad0f317.png)

The parts and assembly shown above can be found in the shared OneDrive folder at: atHome>Brazo>Pinza.

**Comment by Josecisneros001** [comment]
Working on:
- Servos Improvement

**Comment by AlonRuiz** [comment]
Design report: Gripper Iterations

https://docs.google.com/document/d/12_VXpYMRWF4WLSRXYkXUYQPO0zy17tIpcvqSBW9r7Bc/edit?usp=sharing

**Comment by AldoSamaniego** [comment]
![image](https://user-images.githubusercontent.com/47438412/122480789-20101880-cf93-11eb-899e-c1aa5a5b8461.png)
![image](https://user-images.githubusercontent.com/47438412/122480782-1be3fb00-cf93-11eb-8478-84eb136f797b.png)
![image](https://user-images.githubusercontent.com/47438412/122480766-138bc000-cf93-11eb-8998-4a0c70721415.png)
![image](https://user-images.githubusercontent.com/47438412/122480875-50f04d80-cf93-11eb-90bd-92b9797acb50.png)
![image](https://user-images.githubusercontent.com/47438412/122480880-5352a780-cf93-11eb-969a-3ac7b74faa8b.png)
![image](https://user-images.githubusercontent.com/47438412/122480883-551c6b00-cf93-11eb-80cc-2a2ebdffd0b8.png)
