### ISSUE TITLE
Develop Display Integration

### ISSUE THREAD

**Issue by Josecisneros001** [RoBorregos/robocup-home#140]
Objectives:
Design a support for the display.
Deliverables:
SolidWorks CAD

**Comment by BVDozen** [comment]
@AldoSamaniego @AminMendez review the design

**Comment by BVDozen** [comment]
![Captura de pantalla (632)](https://user-images.githubusercontent.com/69731621/112250267-b0ea8880-8c1e-11eb-8b92-a44c05c0793d.png)
![Captura de pantalla (634)](https://user-images.githubusercontent.com/69731621/112250270-b1831f00-8c1e-11eb-8498-5f1133630847.png)
