### ISSUE TITLE
Investigate where to participate

### ISSUE THREAD

**Issue by Josecisneros001** [RoBorregos/robocup-home#141]
Ask
@AldoSamaniego 
@AminMendez

**Comment by IGNA-TENKOV** [comment]
> Ask
> @AldoSamaniego
> @AminMendez

![Screenshot_2](https://user-images.githubusercontent.com/78010403/112223271-4d953200-8bef-11eb-940a-c5190e3df406.jpg)
![Screenshot_9](https://user-images.githubusercontent.com/78010403/112223272-4d953200-8bef-11eb-80e5-f4853fd25953.jpg)

**Comment by IGNA-TENKOV** [comment]
>

**Comment by IGNA-TENKOV** [comment]
![112](https://user-images.githubusercontent.com/78010403/114149745-db0b9e00-98e0-11eb-964d-81c857c1a17c.jpg)
![12123123](https://user-images.githubusercontent.com/78010403/114149748-db0b9e00-98e0-11eb-95d1-09b1de5d9a84.jpg)
