### ISSUE TITLE
Get the 3D image segment of the desired object from the 2D one.

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/Robocup-Home#40]
integrate Cardozo + Iqui to generate 3D image based on 2D image.

Deliverable: PR

**Comment by tomvik** [comment]
@paulvazbad this is being blocked mainly by PR #35 
Also, by the fact that @diegocardozo97 hasn't uploaded his branch with his experiments with the camera, which could help as ground work for us.

**Comment by paulvazbad** [comment]
I have reviewed PR #35 have you talked to @diegocardozo97? I can ping him too if needed.

**Comment by tomvik** [comment]
Now that the PR #35 has been merged, these are the next steps:
1. Check Cardozo's [vision_intel_segment](Robocup-Home/tree/vision_intel_segment) branch and merge whatever is useful
2. Refactor the existing arm_vision package to follow the C++ style guide

**Comment by paulvazbad** [comment]
Are you going to work on both things for the remaining time of this sprint?

**Comment by tomvik** [comment]
That's the plan, but I'm unsure on how much I can complete.

**Comment by tomvik** [comment]
As a follow up:
1. I'm checking Cardozo's branch, soon I should be able to give a LGTM to submit that PR.

2. The refactoring of the existing package is something that @IquiBalamHM was checking, according to our last meeting.

**Comment by tomvik** [comment]
Currently working on refactoring Cardozo's code with the new Python standard.
