### ISSUE TITLE
Draft de las medidas + diseño generico

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/Robocup-Home#43]
Investigar/Hacer algún tipo de estudio para determinar la posición más activa de la pantalla en el robot. Esto involucra integrar con el diseño actual de Aldo y Amin.

Draft de las medidas de los componentes involucrados

Deliverable: Lista, sketch, de las medidas y componentes que afecta la cabeza + pantalla.

**Comment by paulvazbad** [comment]
- Made CAD of the central microphone.
- Determined the optimal position for the screen.
-  Focussing on the face and head.


Deliverable links:

**Comment by paulvazbad** [comment]
@GabrielaMl please add the links to the evidence/deliverables as a comment to this issue.

**Comment by GabrielaMl** [comment]
https://tecmx-my.sharepoint.com/:f:/g/personal/a00825779_itesm_mx/Evrr53hF_7ZPtyLyytkLh-YBqMsqpydhdm7eCWHFch57jg?e=OIB87i
