### ISSUE TITLE
Initial work on main engine + parser

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/Robocup-Home#50]
What needs to be done and how it should be done. 

Deliverable: Document of planned changes to the parser + main engine to complete 2 challenges of stage 1.

Deliverable: Up and running the parser module and main engine.

**Comment by paulvazbad** [comment]
@gabyjazzmin @alexisavz please include here the document that you mentioned to close this issue

**Comment by gabyjazzmin** [comment]
This is the document that we mentioned, here we defined the challenges of stage 1 that we're going to work through this semester https://docs.google.com/document/d/1aLKYcb8XwO975N9op4Mj2bEjEWM1cx5lk2PdpYGhH9k/edit?usp=sharing
