### ISSUE TITLE
search_room algorithm design and implementation

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/robocup-home#53]
Objectives:
- [ ] Documentation design of the algorithm
- [ ] Goal provider v2
- [ ] Goal-path calculator
Note: Objects of interest and room layout will be taken into account.

Deliverable: PR

**Comment by AuroTB** [comment]
Algorithm design: https://docs.google.com/document/d/1FXcqE9BhbKsml0ODm7E16kQts9dipHo5yiBOmtVIvrE/edit#

**Comment by paulvazbad** [comment]
@AuroTB any updates on this?
