### ISSUE TITLE
Arm vision package breaking build

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/Robocup-Home#58]
Steps to recreate:
1. checkout to develop
2. run catkin make
3. an import error appears in the arm vision package.
Image related:
![image](https://user-images.githubusercontent.com/14225515/94382626-11cb5500-0103-11eb-8b2f-bdf16cf91ef2.png)

**Comment by tomvik** [comment]
Basically I didn't catch the error because under my devel folder I still had the my_pcl_tutorial/SegmentedClustersArray msg that was generated when building Iqui's original PR where the package had the name my_pcl_tutorial.
