### ISSUE TITLE
Prototyping new arm

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/robocup-home#76]
Print the pieces of arm
Deliverable: Photos of the pieces and documentation of the process.

**Comment by AuroTB** [comment]
Luis printed some pieces and it's trying to ramp up into using resin to print some pieces (gears)
He's thinking of also doing some modifications to the process (resine stractor) and experimenting with the process.

**Comment by Lufergvera** [comment]
![WhatsApp Image 2020-11-23 at 18 25 23 (2)](https://user-images.githubusercontent.com/63573381/100030725-cd360000-2db9-11eb-90fa-a3a4fa343ba2.jpeg)
I've been some tests with resin gears (washable in water) and I solved ringing problems in the fdm pieces
