### ISSUE TITLE
Unit testing in C++

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/robocup-home#79]
Generate Unit testing for navigation and/or base control. 
Deliverable: Unit tests for the base control/navigation

**Comment by tomvik** [comment]
Once #70 and #82 are done, some tests can be developed.

In the meanwhile, also some code in C++ is being made by @IquiBalamHM for vision, so that could be tested too.

**Comment by tomvik** [comment]
#70 is done.

#82 is on the wait, however now I'm fully occupied with #86
