### ISSUE TITLE
Manufacture arm pulleys

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/robocup-home#96]
Deliverable:
Photos and documentation.

**Comment by Lufergvera** [comment]
![GearT1](https://user-images.githubusercontent.com/63573381/100030636-995ada80-2db9-11eb-9fd9-87a216f64233.png)
![GearT2](https://user-images.githubusercontent.com/63573381/100030640-9a8c0780-2db9-11eb-9883-8551a9afe6b3.png)
![WhatsApp Image 2020-11-23 at 18 25 23 (1)](https://user-images.githubusercontent.com/63573381/100030641-9a8c0780-2db9-11eb-808d-eca572cecadb.jpeg)
![WhatsApp Image 2020-11-23 at 18 25 23](https://user-images.githubusercontent.com/63573381/100030642-9b249e00-2db9-11eb-82a7-cc01958539f0.jpeg)

**Comment by AldoSamaniego** [comment]
![image](https://user-images.githubusercontent.com/47438412/122482164-a75e8b80-cf95-11eb-9e8e-34ec11277ff3.png)
![image](https://user-images.githubusercontent.com/47438412/122482168-a9284f00-cf95-11eb-8c15-20a2bdac38bd.png)
![image](https://user-images.githubusercontent.com/47438412/122482174-aaf21280-cf95-11eb-9499-d298cfaf4f4d.png)
![image](https://user-images.githubusercontent.com/47438412/122482183-b0e7f380-cf95-11eb-9d2d-6e9d2315a28f.png)
![image](https://user-images.githubusercontent.com/47438412/122482193-b2b1b700-cf95-11eb-8f20-eabbd3f2c0c8.png)
![image](https://user-images.githubusercontent.com/47438412/122482200-b5141100-cf95-11eb-828f-b0c593a354a2.png)
