### ISSUE TITLE
Emergency button

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/robocup-home#98]
Deliverable:
CAD and Photos

**Comment by LorenaMGP** [comment]
### **Emergency button**

![BotonParo](https://user-images.githubusercontent.com/68795841/135702322-d27ee69d-2851-470b-95c5-b47ffd9feef8.PNG)

### **Reference**

![Dimensiones](https://user-images.githubusercontent.com/68795841/135702370-9760d0b4-bcc0-469b-ac8e-78246f3942b7.PNG)
[Reference](https://www.se.com/es/es/product/XB4BS8445/paro-de-emergencia%2C-metal%2C-seta-roja%2C-%C3%B840%2C-%C3%B822%2C-giro-del-gatillo-para-liberar%2C-1-no-%2B-1-nc/)

### **Emergency button support**

![Soporte](https://user-images.githubusercontent.com/68795841/135702339-5878228b-df61-42c0-8a39-c20b8dc9785b.PNG)
![Medidas](https://user-images.githubusercontent.com/68795841/135702342-1f90b695-1b82-40cf-82dc-18c0b981e22e.PNG)

### **Example**

![Example](https://user-images.githubusercontent.com/68795841/135702455-ed78002e-ba84-4ea8-86d4-cca125bf7e67.PNG)

### **Some distributors**
[Electrónica universal](https://www.electronicauniversal.com.mx/tienda/botoneras/hpq01k/)
[Lionchip](https://www.lionchipmexico.com/product-page/boton-de-paro-de-emergencia-no-nc-22-mm-plc-push-normalmente)
[Mercado libre](https://articulo.mercadolibre.com.mx/MLM-594492515-boton-paro-de-emergencia-con-enclavamiento-_JM?matt_tool=82503379&matt_word=&matt_source=google&matt_campaign_id=11767285381&matt_ad_group_id=114578050056&matt_match_type=&matt_network=g&matt_device=c&matt_creative=483756468691&matt_keyword=&matt_ad_position=&matt_ad_type=pla&matt_merchant_id=145114835&matt_product_id=MLM594492515&matt_product_partition_id=317785114943&matt_target_id=aud-485761895249:pla-317785114943&gclid=CjwKCAjw7rWKBhAtEiwAJ3CWLCTKRuL7gwsBa8Qwf90WowBiVuv68IIC4TP3ege3lBuEMI5NrGQ7sRoC3UEQAvD_BwE)
